version: "3.9"

services:
  shortener:
    build: ./backend
    ports:
      - "2137:2137"
    env_file:
      - ./backend/.env
  redis-cluster:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - DIR=/opt/redis
    volumes:
      - /opt/redis:/data
